# Creating Arrays

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3 ,4 ,5 , 6 ,7 ,8 ,9 ,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
b = np.array([[[1,2,3 ,4 ,5 ,6], [4, 5, 6 ,7 ,8 ,9]]])
b


array([[[1, 2, 3, 4, 5, 6],
        [4, 5, 6, 7, 8, 9]]])

In [7]:
zeros = np.zeros((4,8))
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
range_array = np.arange(0, 20, 4)
range_array

array([ 0,  4,  8, 12, 16])

In [17]:
linspace_array = np.linspace(0, 1, 5 , )
linspace_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Array Attributes

In [20]:
print(a.shape)

print(b.ndim)

print(b.dtype)


(10,)
3
int64


# Basic Operations


In [24]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])
s = np.array([10,11,12])

print(x+y)
print(z+s)

[5 7 9]
[17 19 21]


In [26]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])
s = np.array([10,11,12])

print(x*y)
print(z*s)

[ 4 10 18]
[ 70  88 108]


# Indexing and Slicing

In [30]:
arr = np.array([[11,22,33], [45,56,67]])

print(arr[0, 1])


22


In [31]:
a = np.array([101, 203, 304, 405])
print(a[[0, 2]])

[101 304]


# Boolean Masking

In [33]:
mask = arr > 9
print(arr[mask])

[11 22 33 45 56 67]


# Reshaping Array

In [38]:
arr



array([[11, 22, 33],
       [45, 56, 67]])

In [43]:
reshaped = arr.reshape((3,2))
reshaped



array([[11, 22],
       [33, 45],
       [56, 67]])

# Stacking Array

In [45]:
a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])
print(np.vstack((a, b ,c)))

[[1 2]
 [3 4]
 [5 6]]


# Splitting Array


In [47]:
x = np.array([[12, 24, 35], [46, 75, 86]])
np.hsplit(x, 3)    
np.vsplit(x, 2)   

[array([[12, 24, 35]]), array([[46, 75, 86]])]

# Broadcasting

In [49]:
a = np.array([140,258,367])
b = np.array([[4],[5],[6]])
print(a, 'next')
print(b)


[140 258 367] next
[[4]
 [5]
 [6]]


# Linear Algebra Operations

In [53]:
from numpy.linalg import inv, eig, svd
matrix = np.array([[111,222], [223,224]] )
matrix

array([[111, 222],
       [223, 224]])

In [55]:
print(inv(matrix))

[[-0.00909017  0.00900901]
 [ 0.00904959 -0.0045045 ]]


In [57]:
eigenvalues, eigenvectors = eig(matrix)
print(eigenvalues)

[-62.06099407 397.06099407]


In [59]:
print(eigenvectors)

[[-0.78867285 -0.61309385]
 [ 0.61481309 -0.79001008]]


In [61]:
U, S, V = svd(matrix)
print(U)

print(S)

print(V)


[[-0.61277504 -0.7902574 ]
 [-0.7902574   0.61277504]]
[397.06228486  62.06079232]
[[-0.61513127 -0.78842471]
 [ 0.78842471 -0.61513127]]


In [63]:
a = np.array([[123, 442], [553, 664]])
b = np.array([[555, 665], [766, 888]])
c = a @ b
c

array([[406837, 474291],
       [815539, 957377]])

In [65]:
np.dot(a, b)

array([[406837, 474291],
       [815539, 957377]])

In [67]:
from numpy.linalg import inv, det
inv_a = inv(a)
inv_a


array([[-0.00407978,  0.00271576],
       [ 0.00339777, -0.00075574]])

In [69]:
det_a = det(a)
det_a


np.float64(-162753.99999999985)

# Random Number Generation

In [77]:
random_floats = np.random.rand(3,2,4,5)
random_floats

array([[[[0.41379066, 0.90695766, 0.99409315, 0.8751446 , 0.2526478 ],
         [0.64162677, 0.94664386, 0.13433503, 0.28915285, 0.99220401],
         [0.9303492 , 0.77228141, 0.28924189, 0.24906292, 0.3643253 ],
         [0.53353747, 0.84513825, 0.30696056, 0.99251201, 0.10128187]],

        [[0.02190941, 0.86991244, 0.25816923, 0.28324189, 0.2175757 ],
         [0.39684066, 0.15037878, 0.29514139, 0.18822501, 0.45573189],
         [0.40619461, 0.4544025 , 0.22954621, 0.85781234, 0.4391949 ],
         [0.71365728, 0.47101719, 0.32791559, 0.76512935, 0.43317275]]],


       [[[0.69646782, 0.88949379, 0.41912188, 0.61023354, 0.68929006],
         [0.15876675, 0.63864189, 0.92292153, 0.49801731, 0.96519025],
         [0.01005694, 0.31248723, 0.96299338, 0.5404511 , 0.67758184],
         [0.42075385, 0.77998892, 0.06055113, 0.15527562, 0.21329744]],

        [[0.13837167, 0.83015779, 0.67069939, 0.09867108, 0.24175901],
         [0.36528224, 0.91316979, 0.04100574, 0.81877037, 0.15973004]

In [79]:
random_integers = np.random.randint(0, 20, size= (3,2))
random_integers

array([[ 1,  2],
       [17,  2],
       [ 9, 18]], dtype=int32)

In [81]:
import numpy as np
np.random.rand(3, 4)

array([[0.06041172, 0.93206964, 0.64799099, 0.2802344 ],
       [0.14194822, 0.23170381, 0.40386403, 0.47235241],
       [0.20103412, 0.4719473 , 0.61936093, 0.49373492]])

In [83]:
np.random.randn(2, 3, 4, 5)

array([[[[-1.07468813e+00,  6.31920960e-01,  2.14749303e+00,
          -1.15846944e+00,  1.16683310e-01],
         [ 4.65756750e-01,  6.73262778e-01,  2.06790432e-01,
           2.13960142e-02, -6.79927952e-01],
         [-9.11915162e-01, -1.04324132e-01,  1.18781110e+00,
          -1.45348345e+00,  2.55449670e-01],
         [-1.11891764e+00,  3.27958997e+00,  4.65966770e-01,
          -8.46128609e-01, -7.82268010e-01]],

        [[-1.28231996e-01,  8.74048147e-02, -3.84476532e-01,
           2.86048837e-01, -1.51216136e-01],
         [-4.68636687e-02, -2.84369629e-01,  2.92919777e+00,
           1.21673196e+00,  1.37688863e-01],
         [-4.98046962e-01,  4.80051369e-01, -3.65040546e-01,
          -2.31738484e+00,  2.71191031e-01],
         [-2.07570130e+00,  2.56575587e-01,  1.80015182e-02,
          -1.02142514e-01, -3.74136632e-01]],

        [[-3.08372277e-01,  6.61790221e-01,  2.84891156e-01,
          -6.18386382e-02, -2.57405861e-03],
         [ 1.01546150e+00, -7.75419986e-01

In [85]:
np.random.randint(1, 50, size=(25, 30))

array([[39, 19, 12, 17, 46,  6, 49, 44, 32, 27, 14, 38, 46, 18, 46, 22,
        19, 10, 10,  8, 22, 32,  9, 13, 23, 18,  9, 26, 37, 27],
       [33, 11, 32, 30, 46, 28, 38, 49, 14, 34, 26, 22, 16,  3, 34, 13,
        10, 33, 14, 28, 18, 47, 19, 12, 18, 12,  5, 43, 23, 40],
       [21, 23,  3, 47, 48, 36, 22, 18, 14, 10, 48, 23, 44, 19, 30, 33,
        23, 26, 20, 42, 46, 40, 37, 17, 25,  4, 27, 17, 19, 17],
       [40, 33, 23, 27, 11, 48, 13, 27, 23, 37,  3, 49, 13,  9, 46, 36,
        36,  7, 13,  1, 40, 27, 31,  7, 41, 36, 28, 15, 42, 34],
       [ 8, 41, 25, 34, 25, 13, 49, 33, 48,  8, 33, 28,  5, 31, 35, 38,
        48, 46, 14, 37,  5, 43, 33, 19,  6,  2, 11, 15, 37, 31],
       [29, 40,  8, 27,  7, 49, 29,  2, 38, 12, 42, 18, 46, 13, 38, 18,
        47,  5, 48, 12,  6, 44, 14, 25, 37, 30, 39,  6, 45,  4],
       [41, 22, 41, 36, 14, 30, 27, 37,  4,  3,  7, 42, 40,  3, 25, 11,
        22, 49, 43,  3,  4, 47, 22, 28, 33, 15, 48,  7, 45, 19],
       [44, 19, 26, 12, 13, 20, 32, 38, 2

In [87]:
a = np.arange(100000)
a

array([    0,     1,     2, ..., 99997, 99998, 99999], shape=(100000,))

# Normalize Rows of a Matrix

In [90]:
def normalize_rows(x):
    return x / np.linalg.norm(x, axis=1, keepdims=True)

matrix = np.random.rand(5, 5)
normalized_matrix = normalize_rows(matrix)
print(normalized_matrix)


[[0.09062631 0.51786666 0.5653292  0.6220528  0.13059174]
 [0.55424617 0.36912835 0.51413655 0.14098152 0.52186518]
 [0.65254028 0.06607912 0.66022618 0.08015943 0.35707226]
 [0.16136494 0.27826729 0.37969448 0.86555024 0.05642304]
 [0.17168937 0.96789602 0.18162512 0.02043645 0.01716745]]


In [92]:
def normalize_rows(x):
    return x / np.linalg.norm(x, axis=1, keepdims=True)

matrix = np.random.rand(10, 10)
normalized_matrix = normalize_rows(matrix)
print(normalized_matrix)


[[4.23216839e-01 5.11374692e-01 2.79055275e-01 2.31267613e-01
  8.08684466e-02 4.36999164e-02 4.34760340e-01 2.17419253e-01
  4.15358048e-01 1.03766542e-01]
 [4.50598078e-01 3.33867797e-01 5.42176205e-02 1.77239654e-01
  3.32929738e-01 7.07262179e-02 2.58175701e-01 2.54954313e-01
  4.57656793e-01 4.40669580e-01]
 [2.25182613e-01 1.23527402e-01 5.17725276e-01 3.67469078e-01
  1.20199069e-01 4.43774560e-01 1.24888555e-01 3.03016278e-01
  4.48135372e-01 1.06469635e-01]
 [4.16691493e-01 2.17596317e-01 3.06141355e-01 2.82104765e-01
  3.40446055e-01 2.95836203e-01 4.02076364e-01 2.45891569e-01
  2.04010113e-01 3.72214517e-01]
 [2.92263416e-02 4.88532031e-01 1.91542228e-01 4.48043458e-01
  1.31307846e-01 4.86791390e-01 4.86694259e-01 1.72561274e-01
  2.03955812e-03 4.68022232e-02]
 [1.18639789e-04 2.49468276e-01 1.80362700e-01 3.81972115e-01
  5.10328102e-01 1.31430182e-01 5.12588965e-01 2.37285436e-01
  2.43767864e-01 3.21168032e-01]
 [4.41673745e-01 3.70022726e-01 2.57107822e-01 4.64820799e

# Custom Universal Function

In [94]:
def custom_func(x):
    return x**2 + 2*x + 1
vectorized_func = np.vectorize(custom_func)
arr = np.array([11, 22, 33])
print(vectorized_func(arr))

[ 144  529 1156]


# Memory Efficiency: Views vs. Copies

In [96]:
a = np.arange(100)
b = a[::10]  
b[0] = 1000
print(a)   

[1000    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99]


# Advanced Indexing


In [98]:
arr = np.array([[134, 245], [345, 466], [545, 656]])
indices = ([0, 1, 2], [1, 0, 1])
print(arr[indices]) 

[245 345 656]


# Vectorization


In [100]:
a = [1, 2, 3, 4]
b = [x**2 for x in a]
a

[1, 2, 3, 4]

In [102]:
b

[1, 4, 9, 16]

In [105]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = a ** 2  
a


array([1, 2, 3, 4])

In [107]:
b

array([ 1,  4,  9, 16])

In [123]:
%timeit [x**2 for x in range(100000)]        
%timeit np.arange(100000) ** 2   

13 ms ± 589 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
134 μs ± 2.83 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# C-order vs Fortran-order

In [125]:
a = np.array([[1, 2], [3, 4]], order='C')


In [127]:
a

array([[1, 2],
       [3, 4]])

In [128]:
b

array([ 1,  4,  9, 16])

# Memory Info


In [130]:
a = np.array([[13, 42], [43, 45]])
a


array([[13, 42],
       [43, 45]])

In [132]:
print(a.nbytes)

32


In [133]:
print(a.strides)

(16, 8)
